### ISSUE TITLE
script failed!: addon.py

### ISSUE THREAD

**Issue by michnik** [jbeluch/plugin.video.documentary.net#2]
I'm getting this message when I try to run this plugin. It was working for me about 2 weeks ago. I've tried to reinstalling the plugin, but no luck. Would you require a log files to examine this issue?

**Comment by jbeluch** [comment]
Thanks for the report, I'll take a look. A copy of your xbmc.log file always helps though.

**Comment by jbeluch** [comment]
Seems they changed their API. I've updated the addon, it should show up in the official repo in a day or so.

**Comment by michnik** [comment]
Thanks a million!

It works now on my end.

Cheers

**Comment by davercooke** [comment]
Hi, I'm receiving the same error when trying to launch Documentary.net v 1.1 on XBMC 12.2. I tried installing it today, October 1st, 2013.
Thanks,
Dave

**Comment by ranom** [comment]
I am having the same issue as the poster above. Has the API changed once again? I just installed v1.1 on Eden on OSX.
